name: generate-shared-lib

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu-20.04
            os_name: linux
          - os: macos-11
            os_name: darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build shared lib
        run: make gen-flocgo-${{ matrix.os_name }}

      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: floc/floc_go
          default_author: github_actions
          message: Updates shared lib (${{ matrix.os_name }})
